// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: spire/api/types/spiffeidtemplate.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SPIFFEIDTemplate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SpiffeIdTemplate string                 `protobuf:"bytes,2,opt,name=spiffe_id_template,json=spiffeIdTemplate,proto3" json:"spiffe_id_template,omitempty"`
	ParentId         *SPIFFEID              `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Selectors        []*Selector            `protobuf:"bytes,4,rep,name=selectors,proto3" json:"selectors,omitempty"`
	FederatesWith    []string               `protobuf:"bytes,5,rep,name=federates_with,json=federatesWith,proto3" json:"federates_with,omitempty"`
	X509SvidTtl      int32                  `protobuf:"varint,6,opt,name=x509_svid_ttl,json=x509SvidTtl,proto3" json:"x509_svid_ttl,omitempty"`
	JwtSvidTtl       int32                  `protobuf:"varint,7,opt,name=jwt_svid_ttl,json=jwtSvidTtl,proto3" json:"jwt_svid_ttl,omitempty"`
	RevisionNumber   int64                  `protobuf:"varint,8,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	StoreSvid        bool                   `protobuf:"varint,9,opt,name=store_svid,json=storeSvid,proto3" json:"store_svid,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SPIFFEIDTemplate) Reset() {
	*x = SPIFFEIDTemplate{}
	mi := &file_spire_api_types_spiffeidtemplate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SPIFFEIDTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPIFFEIDTemplate) ProtoMessage() {}

func (x *SPIFFEIDTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_spire_api_types_spiffeidtemplate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPIFFEIDTemplate.ProtoReflect.Descriptor instead.
func (*SPIFFEIDTemplate) Descriptor() ([]byte, []int) {
	return file_spire_api_types_spiffeidtemplate_proto_rawDescGZIP(), []int{0}
}

func (x *SPIFFEIDTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SPIFFEIDTemplate) GetSpiffeIdTemplate() string {
	if x != nil {
		return x.SpiffeIdTemplate
	}
	return ""
}

func (x *SPIFFEIDTemplate) GetParentId() *SPIFFEID {
	if x != nil {
		return x.ParentId
	}
	return nil
}

func (x *SPIFFEIDTemplate) GetSelectors() []*Selector {
	if x != nil {
		return x.Selectors
	}
	return nil
}

func (x *SPIFFEIDTemplate) GetFederatesWith() []string {
	if x != nil {
		return x.FederatesWith
	}
	return nil
}

func (x *SPIFFEIDTemplate) GetX509SvidTtl() int32 {
	if x != nil {
		return x.X509SvidTtl
	}
	return 0
}

func (x *SPIFFEIDTemplate) GetJwtSvidTtl() int32 {
	if x != nil {
		return x.JwtSvidTtl
	}
	return 0
}

func (x *SPIFFEIDTemplate) GetRevisionNumber() int64 {
	if x != nil {
		return x.RevisionNumber
	}
	return 0
}

func (x *SPIFFEIDTemplate) GetStoreSvid() bool {
	if x != nil {
		return x.StoreSvid
	}
	return false
}

func (x *SPIFFEIDTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

var File_spire_api_types_spiffeidtemplate_proto protoreflect.FileDescriptor

const file_spire_api_types_spiffeidtemplate_proto_rawDesc = "" +
	"\n" +
	"&spire/api/types/spiffeidtemplate.proto\x12\x0fspire.api.types\x1a\x1espire/api/types/selector.proto\x1a\x1espire/api/types/spiffeid.proto\"\x95\x03\n" +
	"\x10SPIFFEIDTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12spiffe_id_template\x18\x02 \x01(\tR\x10spiffeIdTemplate\x126\n" +
	"\tparent_id\x18\x03 \x01(\v2\x19.spire.api.types.SPIFFEIDR\bparentId\x127\n" +
	"\tselectors\x18\x04 \x03(\v2\x19.spire.api.types.SelectorR\tselectors\x12%\n" +
	"\x0efederates_with\x18\x05 \x03(\tR\rfederatesWith\x12\"\n" +
	"\rx509_svid_ttl\x18\x06 \x01(\x05R\vx509SvidTtl\x12 \n" +
	"\fjwt_svid_ttl\x18\a \x01(\x05R\n" +
	"jwtSvidTtl\x12'\n" +
	"\x0frevision_number\x18\b \x01(\x03R\x0erevisionNumber\x12\x1d\n" +
	"\n" +
	"store_svid\x18\t \x01(\bR\tstoreSvid\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\x03R\tcreatedAtB7Z5github.com/spiffe/spire-api-sdk/proto/spire/api/typesb\x06proto3"

var (
	file_spire_api_types_spiffeidtemplate_proto_rawDescOnce sync.Once
	file_spire_api_types_spiffeidtemplate_proto_rawDescData []byte
)

func file_spire_api_types_spiffeidtemplate_proto_rawDescGZIP() []byte {
	file_spire_api_types_spiffeidtemplate_proto_rawDescOnce.Do(func() {
		file_spire_api_types_spiffeidtemplate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_spire_api_types_spiffeidtemplate_proto_rawDesc), len(file_spire_api_types_spiffeidtemplate_proto_rawDesc)))
	})
	return file_spire_api_types_spiffeidtemplate_proto_rawDescData
}

var file_spire_api_types_spiffeidtemplate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_spire_api_types_spiffeidtemplate_proto_goTypes = []any{
	(*SPIFFEIDTemplate)(nil), // 0: spire.api.types.SPIFFEIDTemplate
	(*SPIFFEID)(nil),         // 1: spire.api.types.SPIFFEID
	(*Selector)(nil),         // 2: spire.api.types.Selector
}
var file_spire_api_types_spiffeidtemplate_proto_depIdxs = []int32{
	1, // 0: spire.api.types.SPIFFEIDTemplate.parent_id:type_name -> spire.api.types.SPIFFEID
	2, // 1: spire.api.types.SPIFFEIDTemplate.selectors:type_name -> spire.api.types.Selector
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_spire_api_types_spiffeidtemplate_proto_init() }
func file_spire_api_types_spiffeidtemplate_proto_init() {
	if File_spire_api_types_spiffeidtemplate_proto != nil {
		return
	}
	file_spire_api_types_selector_proto_init()
	file_spire_api_types_spiffeid_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_spire_api_types_spiffeidtemplate_proto_rawDesc), len(file_spire_api_types_spiffeidtemplate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_spire_api_types_spiffeidtemplate_proto_goTypes,
		DependencyIndexes: file_spire_api_types_spiffeidtemplate_proto_depIdxs,
		MessageInfos:      file_spire_api_types_spiffeidtemplate_proto_msgTypes,
	}.Build()
	File_spire_api_types_spiffeidtemplate_proto = out.File
	file_spire_api_types_spiffeidtemplate_proto_goTypes = nil
	file_spire_api_types_spiffeidtemplate_proto_depIdxs = nil
}
